name: Nasa Project CLI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node.js version 22
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - run: npm run configure
      - run: npm run build --prefix client